// AI Primers Service
// Loads and manages AI primer cards from scraped data

import type { AIPrimerCard, AIPrimersIndex } from '../types/ai-primers'
import type { KnowledgeGraph } from '../types/graph'

// We'll import the JSON data - these will be generated by the scraper
// For now, create placeholder functions that will work once data is available

let cachedCards: AIPrimerCard[] | null = null
let cachedGraph: KnowledgeGraph | null = null
let cachedIndex: AIPrimersIndex | null = null

// Load the index
export async function loadIndex(): Promise<AIPrimersIndex | null> {
  if (cachedIndex) return cachedIndex
  
  try {
    // Dynamic import of JSON data
    const indexData = require('../../data/ai-primers/index.json')
    cachedIndex = indexData
    return indexData
  } catch (error) {
    console.warn('AI Primers index not found. Run scraper first.')
    return null
  }
}

// Load all cards
export async function loadAllCards(): Promise<AIPrimerCard[]> {
  if (cachedCards) return cachedCards
  
  try {
    const cardsData = require('../../data/ai-primers/all-cards.json')
    cachedCards = cardsData
    return cardsData
  } catch (error) {
    console.warn('AI Primers cards not found. Run scraper first.')
    return []
  }
}

// Load the knowledge graph
export async function loadGraph(): Promise<KnowledgeGraph | null> {
  if (cachedGraph) return cachedGraph
  
  try {
    const graphData = require('../../data/graphs/ai-primers-graph.json')
    cachedGraph = graphData
    return graphData
  } catch (error) {
    console.warn('AI Primers graph not found. Run graph builder first.')
    return null
  }
}

// Get a card by ID
export async function getCardById(cardId: string): Promise<AIPrimerCard | null> {
  const cards = await loadAllCards()
  return cards.find(c => c.id === cardId) || null
}

// Get cards by category
export async function getCardsByCategory(category: string): Promise<AIPrimerCard[]> {
  const cards = await loadAllCards()
  return cards.filter(c => 
    c.category.toLowerCase().includes(category.toLowerCase())
  )
}

// Get cards by article
export async function getCardsByArticle(articleSlug: string): Promise<AIPrimerCard[]> {
  const cards = await loadAllCards()
  return cards.filter(c => c.articleSlug === articleSlug)
}

// Get random cards for discovery
export function getRandomCards(cards: AIPrimerCard[], count: number = 20): AIPrimerCard[] {
  const shuffled = [...cards].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}

// Get beginner-friendly cards
export function getBeginnerCards(cards: AIPrimerCard[], count: number = 20): AIPrimerCard[] {
  const beginnerCards = cards.filter(c => c.difficulty <= 2)
  return getRandomCards(beginnerCards, count)
}

// Search cards by title or tags
export function searchCards(cards: AIPrimerCard[], query: string): AIPrimerCard[] {
  const lowerQuery = query.toLowerCase()
  return cards.filter(c => 
    c.title.toLowerCase().includes(lowerQuery) ||
    c.article.toLowerCase().includes(lowerQuery) ||
    c.tags.some(t => t.toLowerCase().includes(lowerQuery))
  )
}

// Get related cards using the graph
export async function getRelatedCards(
  cardId: string, 
  limit: number = 5
): Promise<AIPrimerCard[]> {
  const graph = await loadGraph()
  const cards = await loadAllCards()
  
  if (!graph) return []
  
  const adj = graph.adjacencyList[cardId]
  if (!adj) return []
  
  const relatedIds = [...adj.related, ...adj.next].slice(0, limit)
  return relatedIds
    .map(id => cards.find(c => c.id === id))
    .filter((c): c is AIPrimerCard => c !== null)
}

// Get next cards in sequence
export async function getNextCards(cardId: string): Promise<AIPrimerCard[]> {
  const graph = await loadGraph()
  const cards = await loadAllCards()
  
  if (!graph) return []
  
  const adj = graph.adjacencyList[cardId]
  if (!adj) return []
  
  return adj.next
    .map(id => cards.find(c => c.id === id))
    .filter((c): c is AIPrimerCard => c !== null)
}

// Get sibling cards (same article)
export async function getSiblingCards(cardId: string): Promise<AIPrimerCard[]> {
  const graph = await loadGraph()
  const cards = await loadAllCards()
  
  if (!graph) return []
  
  const adj = graph.adjacencyList[cardId]
  if (!adj) return []
  
  return adj.siblings
    .map(id => cards.find(c => c.id === id))
    .filter((c): c is AIPrimerCard => c !== null)
}

// Clear cache (useful for refreshing data)
export function clearCache(): void {
  cachedCards = null
  cachedGraph = null
  cachedIndex = null
}

